steps:
# Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/book-management-api/book-management-api:$COMMIT_SHA', '.']
# Deploy
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/book-management-api/book-management-api:$COMMIT_SHA']