version: '3'
services: 
    app:
        container_name: book-management-api
        restart: always
        build: .
        ports:
            - '3100:3100'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
